services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile

  gitea:
    image: docker.gitea.com/gitea:1.24.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    # networks:
    #   - gitea
    volumes:
      - gitea:/data
      - ./gitea.db:/data/gitea/gitea.db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    
volumes:
  gitea:
    driver: local