name: Publish Go Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g. v1.2.3)"
        required: true
        type: string
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Tidy modules
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Notify Go Proxy
        run: go list -m agithub.com/tvandinther/gitops-manager@${{ github.ref_name }}
        env:
          GOPROXY: "proxy.golang.org"
